POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "Suhail Malik",
  "email": "devmsuhail@gmail.com",
  "password": "Suhail80@"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "devmsuhail@gmail.com",
  "password": "Suhail80@"
}